name: run-tests
on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  run-tests:
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set ARCHFLAGS for macOS
        if: runner.os == 'macOS'
        run: echo "ARCHFLAGS=-arch arm64" >> $GITHUB_ENV

      - name: Install poetry
        run: python -m pip install poetry

      - name: Cache the virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-${{ matrix.python }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: python -m poetry install

      - name: Run tests and Generate coverage
        run: |
          poetry run pytest --cov --cov-report=xml -v --full-trace

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON
